# Generated by Django 5.1.4 on 2024-12-17 15:56

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Divida',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('contribuinte', models.CharField(max_length=255)),
                ('valor_principal', models.DecimalField(decimal_places=2, max_digits=10)),
                ('multa', models.DecimalField(decimal_places=2, max_digits=5)),
                ('juros', models.DecimalField(decimal_places=2, max_digits=5)),
                ('data_vencimento', models.DateField()),
            ],
        ),
        migrations.CreateModel(
            name='OpcaoNegociacao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(max_length=50)),
                ('desconto_multa', models.DecimalField(decimal_places=2, max_digits=5)),
                ('desconto_juros', models.DecimalField(decimal_places=2, max_digits=5)),
                ('parcelas', models.IntegerField(blank=True, null=True)),
                ('divida', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='negociacao.divida')),
            ],
        ),
    ]
