# Generated by Django 5.1.4 on 2024-12-17 17:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('negociacao', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='divida',
            name='juros',
            field=models.DecimalField(decimal_places=2, max_digits=10),
        ),
        migrations.AlterField(
            model_name='divida',
            name='multa',
            field=models.DecimalField(decimal_places=2, max_digits=10),
        ),
    ]
