# Generated by Django 5.1.4 on 2024-12-17 20:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('negociacao', '0002_alter_divida_juros_alter_divida_multa'),
    ]

    operations = [
        migrations.RenameField(
            model_name='divida',
            old_name='valor_principal',
            new_name='valor',
        ),
        migrations.RemoveField(
            model_name='divida',
            name='data_vencimento',
        ),
        migrations.AddField(
            model_name='divida',
            name='cnpj',
            field=models.CharField(blank=True, max_length=14, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='divida',
            name='cpf',
            field=models.CharField(blank=True, max_length=11, null=True, unique=True),
        ),
        migrations.DeleteModel(
            name='OpcaoNegociacao',
        ),
    ]
