# Generated by Django 5.1.4 on 2024-12-17 21:00

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('negociacao', '0004_rename_valor_divida_valor_principal_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='OpcaoNegociacao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(choices=[('à vista', 'À Vista'), ('parcelado', 'Parcelado')], max_length=50)),
                ('desconto_multa', models.DecimalField(decimal_places=2, help_text='Desconto sobre a multa (%)', max_digits=5)),
                ('desconto_juros', models.DecimalField(decimal_places=2, help_text='Desconto sobre os juros (%)', max_digits=5)),
                ('parcelas', models.IntegerField(blank=True, help_text='Quantidade de parcelas (somente para parcelamento)', null=True)),
                ('divida', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='opcoes_negociacao', to='negociacao.divida')),
            ],
        ),
    ]
