# Generated by Django 5.1.4 on 2024-12-17 21:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('negociacao', '0005_opcaonegociacao'),
    ]

    operations = [
        migrations.AlterField(
            model_name='divida',
            name='cnpj',
            field=models.CharField(blank=True, max_length=14, null=True),
        ),
        migrations.AlterField(
            model_name='divida',
            name='cpf',
            field=models.CharField(blank=True, max_length=11, null=True),
        ),
        migrations.AlterField(
            model_name='divida',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
