# Generated by Django 5.1.4 on 2024-12-30 12:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('negociacao', '0006_alter_divida_cnpj_alter_divida_cpf_alter_divida_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='opcaonegociacao',
            name='descricao',
            field=models.TextField(blank=True, help_text='Descrição detalhada da opção de negociação', null=True),
        ),
        migrations.AlterField(
            model_name='opcaonegociacao',
            name='tipo',
            field=models.CharField(choices=[('à vista', 'À Vista'), ('parcelado', 'Parcelado'), ('refis', 'Refis'), ('transacao_tributaria', 'Transação Tributária'), ('compensacao_creditos', 'Compensação de Créditos'), ('suspensao_cobranca', 'Suspensão da Cobrança')], max_length=50),
        ),
    ]
