# Generated by Django 5.1.4 on 2024-12-30 16:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('negociacao', '0007_opcaonegociacao_descricao_alter_opcaonegociacao_tipo'),
    ]

    operations = [
        migrations.AddField(
            model_name='opcaonegociacao',
            name='juros',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Juros aplicados nas parcelas', max_digits=5, null=True),
        ),
    ]
